# Generated by Django 2.1.5 on 2022-08-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_ocrtext_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='application',
            field=models.CharField(choices=[(1, 'Application')], default='', max_length=6),
        ),
    ]
